pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                    args '-u 0' // Explicitly run as root
                    
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test ./... -v'
                }
            }
        }
    }
}
